export const expressDeliveryOrder = {
  id: 11111111,
  email: "dddd@dd.com",
  closed_at: null,
  created_at: "2018-11-22T12:54:55+01:00",
  updated_at: "2018-11-28T13:19:47+01:00",
  number: 111,
  note: "",
  token: "1111111",
  gateway: "Rechnungskauf",
  test: false,
  taxes_included: true,
  currency: "EUR",
  financial_status: "pending",
  confirmed: true,
  total_discounts: "0.00",
  total_line_items_price: "590.00",
  cart_token: "413a09554204033e3c1c8210ab09d3af",
  buyer_accepts_marketing: false,
  name: "#11602",
  referring_site: "",
  landing_site: "/collections/",
  cancelled_at: null,
  cancel_reason: null,
  checkout_token: "e52d1923192b120642e75f03c7541117",
  reference: null,
  user_id: null,
  location_id: null,
  source_identifier: null,
  source_url: null,
  processed_at: "2018-11-22T12:54:55+01:00",
  device_id: null,
  phone: null,
  customer_locale: "de",
  app_id: 1111,
  landing_site_ref: null,
  order_number: 11602,
  discount_applications: [],
  discount_codes: [],
  note_attributes: [],
  payment_gateway_names: ["Rechnungskauf"],
  processing_method: "manual",
  checkout_id: 7186676187226,
  source_name: "web",
  fulfillment_status: "fulfilled",
  tax_lines: [
    {
      price: "98.99",
      rate: 0.19,
      title: "MwSt",
      price_set: {
        shop_money: {
          amount: "98.99",
          currency_code: "EUR",
        },
        presentment_money: {
          amount: "98.99",
          currency_code: "EUR",
        },
      },
    },
  ],
  tags: "",
  contact_email: "dd@dd.de",
  order_status_url: "http",
  presentment_currency: "EUR",
  total_line_items_price_set: {
    shop_money: {
      amount: "123.00",
      currency_code: "EUR",
    },
    presentment_money: {
      amount: "123.00",
      currency_code: "EUR",
    },
  },
  total_discounts_set: {
    shop_money: {
      amount: "0.00",
      currency_code: "EUR",
    },
    presentment_money: {
      amount: "0.00",
      currency_code: "EUR",
    },
  },
  total_shipping_price_set: {
    shop_money: {
      amount: "123.00",
      currency_code: "EUR",
    },
    presentment_money: {
      amount: "123.00",
      currency_code: "EUR",
    },
  },
  subtotal_price_set: {
    shop_money: {
      amount: "123.00",
      currency_code: "EUR",
    },
    presentment_money: {
      amount: "123.00",
      currency_code: "EUR",
    },
  },
  total_price_set: {
    shop_money: {
      amount: "123.00",
      currency_code: "EUR",
    },
    presentment_money: {
      amount: "123.00",
      currency_code: "EUR",
    },
  },
  total_tax_set: {
    shop_money: {
      amount: "123.99",
      currency_code: "EUR",
    },
    presentment_money: {
      amount: "123.99",
      currency_code: "EUR",
    },
  },
  line_items: [
    {
      id: 16350496794,
      variant_id: 2181085211,
      title: "title",
      quantity: 2,
      sku: "221-003",
      variant_title: "",
      vendor: "innnnp",
      fulfillment_service: "manual",
      product_id: 1684190235,
      requires_shipping: true,
      taxable: true,
      gift_card: false,
      name: "ddd",
      variant_inventory_management: null,
      properties: [],
      product_exists: true,
      fulfillable_quantity: 0,
      grams: 6800,
      price: "13.00",
      total_discount: "0.00",
      fulfillment_status: "fulfilled",
      price_set: {
        shop_money: {
          amount: "123.00",
          currency_code: "EUR",
        },
        presentment_money: {
          amount: "123.00",
          currency_code: "EUR",
        },
      },
      total_discount_set: {
        shop_money: {
          amount: "0.00",
          currency_code: "EUR",
        },
        presentment_money: {
          amount: "0.00",
          currency_code: "EUR",
        },
      },
      discount_allocations: [],
      admin_graphql_api_id: "gid://shopify/LineItem/1635794",
      tax_lines: [
        {
          title: "MwSt",
          price: "123.20",
          rate: 0.19,
          price_set: {
            shop_money: {
              amount: "123.20",
              currency_code: "EUR",
            },
            presentment_money: {
              amount: "123.20",
              currency_code: "EUR",
            },
          },
        },
      ],
      origin_location: {
        id: 1196900507,
        country_code: "DE",
        province_code: "",
        name: "name",
        address1: "Karl",
        address2: "Company",
        city: "B",
        zip: "12222",
      },
      destination_location: {
        id: 664639322,
        country_code: "DE",
        province_code: "",
        name: "name",
        address1: "add 1",
        address2: "add 2",
        city: "city",
        zip: "123446",
      },
    },
  ],
  refunds: [],
  total_tip_received: "0.0",
  admin_graphql_api_id: "gid://shopify/Order/11111111",
  shipping_lines: [
    {
      id: 81839372,
      title: "Express Versand",
      price: "123.00",
      code: "Express Versand",
      source: "shopify",
      phone: null,
      requested_fulfillment_service_id: null,
      delivery_category: null,
      carrier_identifier: null,
      discounted_price: "123.00",
      price_set: {
        shop_money: {
          amount: "123.00",
          currency_code: "EUR",
        },
        presentment_money: {
          amount: "123.00",
          currency_code: "EUR",
        },
      },
      discounted_price_set: {
        shop_money: {
          amount: "123.00",
          currency_code: "EUR",
        },
        presentment_money: {
          amount: "123.00",
          currency_code: "EUR",
        },
      },
      discount_allocations: [],
      tax_lines: [
        {
          title: "MwSt",
          price: "123.79",
          rate: 0.19,
          price_set: {
            shop_money: {
              amount: "123.79",
              currency_code: "EUR",
            },
            presentment_money: {
              amount: "123.79",
              currency_code: "EUR",
            },
          },
        },
      ],
    },
  ],
  billing_address: {
    first_name: "first",
    address1: "address 11",
    phone: "+49 303 30303",
    city: "B",
    zip: "12345",
    province: null,
    country: "Germany",
    last_name: "last",
    address2: "",
    company: "comp",
    latitude: 48.0,
    longitude: 11.0,
    name: "name",
    country_code: "DE",
    province_code: null,
  },
  shipping_address: {
    first_name: "fist",
    address1: "adress 70",
    phone: "+49 173 1231231",
    city: "city",
    zip: "1234",
    province: null,
    country: "Germany",
    last_name: "last",
    address2: "addd 2",
    company: "comp",
    latitude: 48.0,
    longitude: 11.5,
    name: "name",
    country_code: "DE",
    province_code: null,
  },
  customer: {
    id: 1234444,
    email: "test@tets.de",
    accepts_marketing: false,
    created_at: "2018-11-22T08:54:35+01:00",
    updated_at: "2019-06-18T11:55:39+02:00",
    first_name: "first",
    last_name: "last",
    orders_count: 4,
    state: "disabled",
    total_spent: "123.00",
    last_order_id: 776858,
    note: null,
    verified_email: true,
    multipass_identifier: null,
    tax_exempt: false,
    phone: null,
    tags: "",
    last_order_name: "123",
    currency: "EUR",
    default_address: {
      id: 123123,
      customer_id: 12312321,
      first_name: "first",
      last_name: "last",
      company: "comp",
      address1: "add1",
      address2: "",
      city: "city",
      province: "",
      country: "de",
      zip: "12345",
      phone: "+49 30300303",
      name: "ame",
      province_code: null,
      country_code: "de",
      country_name: "ede",
      default: true,
    },
  },
};
